version: "3.8"

services:
  app:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
      - ./configs:/app/configs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - APP_MODULE=src.main:app
    # command:  # Original command commented out
    #   [
    #     "conda",
    #     "run",
    #     "-n",
    #     "egypt-tourism1",
    #     "uvicorn",
    #     "src.main:app",
    #     "--host",
    #     "0.0.0.0",
    #     "--port",
    #     "5050",
    #   ]
    command: # New command using direct python invocation
      [
        "/opt/conda/envs/egypt-tourism1/bin/python",
        "-m",
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "5050",
      ]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    depends_on:
      - redis
      - db_postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  db_postgres:
    image: postgres:15
    container_name: egypt_chatbot_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: egypt_chatbot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d egypt_chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  postgres_data:
    driver: local
